### ISSUE TITLE
Provide option to wrap toc in details tag

### ISSUE THREAD

**Issue by meblum** [abhinav/goldmark-toc#41]
Provide an option to render the toc as a details tag so it can be auto formatted in the browser as an expandable list:
<details>
  <summary>Table of Contents</summary>
      <ul>
          <li>list item one</li>
          <li>list item two</li>
      </ul>
</details>

```
<details>
  <summary>Table of Contents</summary>
      <ul>
          <li>list item one</li>
          <li>list item two</li>
      </ul>
</details>
```

**Comment by abhinav** [comment]
For something that specific, I don't think goldmark-toc should implement that.

Part of the problem here is that Markdown or Commonmark doesn't have a native concept for `<details>` or `<summary>`, so you end up needing plain HTML blocks.

goldmark-toc can give you an [`ast.List`](https://pkg.go.dev/github.com/yuin/goldmark/ast#List) for your table of contents, but surrounding that with raw HTML is a bit difficult.  Your best bet there is to define a custom AST node and register a block renderer for it. It's not too difficult to do this if you look at how other extensions do a node renderer. (You don't need to write a parser for it.)

So you need a block node that gets generated into `<details>`, `<summary>$some text</summary>`, and `</details>`, and add the `ast.List` provided by goldmark-toc to that as a child. (You'll need to use the [manual method](https://github.com/abhinav/goldmark-toc#manual) of generating a TOC to get this ast.List.)

**Comment by meblum** [comment]
Makes sense. Thanks, closing this for now
